import { useState } from 'react';
import { Badge, Card, Button, PageHeader } from '@/components';
import { ManagerLayout } from '@/layouts';
import { AlertCircle, CheckCircle2, EyeOff, ShieldAlert } from 'lucide-react';
import { toast } from 'sonner';

interface AlertItem {
  id: string;
  employeeName: string;
  type: string;
  severity: 'low' | 'medium' | 'high';
  status: 'active' | 'resolved' | 'dismissed';
  date: string;
  description: string;
}

const MOCK_ALERTS: AlertItem[] = [
  {
    id: 'alt-1', employeeName: 'Emily Davis',   type: 'Consecutive Low Mood', severity: 'high',
    status: 'active',   date: '2026-08-08',
    description: 'Emily Davis logged a mood score of 2 or less for three consecutive work days.',
  },
  {
    id: 'alt-2', employeeName: 'David Wilson',  type: 'Acute Stress Spike',   severity: 'medium',
    status: 'active',   date: '2026-08-07',
    description: 'David Wilson registered a self-reported stress rating of 5 (Very High) with low sleep.',
  },
  {
    id: 'alt-3', employeeName: 'Michael Brown', type: 'Gradual Trend Drop',    severity: 'low',
    status: 'resolved', date: '2026-08-05',
    description: "Michael Brown's 7-day mood index average dropped below the team baseline of 3.0.",
  },
];

const severityConfig: Record<string, { border: string; bg: string; iconColor: string }> = {
  high:   { border: 'border-l-rose-500',   bg: 'bg-rose-50/70',   iconColor: 'text-rose-600' },
  medium: { border: 'border-l-amber-500',  bg: 'bg-amber-50/70',  iconColor: 'text-amber-600' },
  low:    { border: 'border-l-emerald-500', bg: 'bg-emerald-50/70', iconColor: 'text-emerald-600' },
};

export default function ManagerAlerts() {
  const [alerts, setAlerts] = useState<AlertItem[]>(MOCK_ALERTS);
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'resolved'>('all');

  function handleResolve(id: string) {
    setAlerts((prev) => prev.map((a) => a.id === id ? { ...a, status: 'resolved' as const } : a));
    toast.success('Alert marked as resolved successfully');
  }

  function handleDismiss(id: string) {
    setAlerts((prev) => prev.map((a) => a.id === id ? { ...a, status: 'dismissed' as const } : a));
    toast.success('Alert dismissed from active feed');
  }

  const filteredAlerts = alerts.filter((a) => {
    if (statusFilter === 'all') return a.status !== 'dismissed';
    return a.status === statusFilter;
  });

  const TABS = [
    { key: 'all',      label: 'All Active & Resolved' },
    { key: 'active',   label: 'Needs Attention (Active)' },
    { key: 'resolved', label: 'Resolved History' },
  ] as const;

  return (
    <ManagerLayout>
      <div className="flex w-full flex-col gap-6 animate-fadeIn">
        <PageHeader
          title="Team Risk & Burnout Alerts"
          subtitle="Automated alerts generated by statistical trend analysis and early burnout detection models"
          action={
            <div className="flex rounded-xl border border-zinc-200/80 bg-zinc-100 p-1">
              {TABS.map(({ key, label }) => (
                <button
                  key={key}
                  type="button"
                  onClick={() => setStatusFilter(key)}
                  className={[
                    'px-4 py-2 text-xs font-bold rounded-lg transition-all duration-150 border-none cursor-pointer',
                    statusFilter === key
                      ? 'bg-white text-zinc-900 shadow-sm'
                      : 'bg-transparent text-zinc-500 hover:text-zinc-900',
                  ].join(' ')}
                >
                  {label}
                </button>
              ))}
            </div>
          }
        />

        {/* ── Alert Cards Feed ── */}
        <div className="flex flex-col gap-6">
          {filteredAlerts.length === 0 ? (
            <Card className="text-center py-16 text-zinc-400">
              <ShieldAlert size={36} className="mx-auto mb-3 opacity-40 text-emerald-500" />
              <p className="text-base font-bold text-zinc-700 m-0">No alerts found in this view</p>
              <p className="text-xs text-zinc-400 mt-1">All team members are reporting healthy wellness metrics</p>
            </Card>
          ) : (
            filteredAlerts.map((alt) => {
              const cfg = severityConfig[alt.severity] ?? severityConfig.low;
              return (
                <Card
                  key={alt.id}
                  className={`flex flex-col gap-6 border-l-4 ${cfg.border} p-8 sm:p-10 hover:border-zinc-300`}
                >
                  <div className="flex flex-wrap items-start justify-between gap-4">
                    <div className="flex items-center gap-4">
                      <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${cfg.bg} ${cfg.iconColor}`}>
                        <AlertCircle size={22} />
                      </div>
                      <div>
                        <h3 className="text-base font-extrabold text-zinc-900 m-0">
                          {alt.type} · <span className="text-[#00C853]">{alt.employeeName}</span>
                        </h3>
                        <span className="text-xs text-zinc-400 font-medium mt-0.5 block">
                          Triggered on {alt.date} via automated telemetry check
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-4 flex-wrap">
                      <Badge variant={alt.severity}>{alt.severity.toUpperCase()} RISK</Badge>
                      <Badge variant={alt.status}>{alt.status.toUpperCase()}</Badge>
                    </div>
                  </div>

                  <p className="text-sm text-zinc-600 leading-relaxed m-0 bg-zinc-50/80 p-4 rounded-xl border border-zinc-100">
                    {alt.description}
                  </p>

                  {alt.status === 'active' && (
                    <div className="flex items-center justify-end gap-4 pt-4 border-t border-zinc-100">
                      <Button
                        variant="secondary"
                        size="sm"
                        leftIcon={<EyeOff size={14} />}
                        onClick={() => handleDismiss(alt.id)}
                        className="font-semibold text-zinc-600 hover:text-zinc-900"
                      >
                        Dismiss Alert
                      </Button>
                      <Button
                        variant="primary"
                        size="sm"
                        leftIcon={<CheckCircle2 size={14} />}
                        onClick={() => handleResolve(alt.id)}
                        className="font-bold shadow-md shadow-[#00E676]/20"
                      >
                        Mark as Resolved
                      </Button>
                    </div>
                  )}
                </Card>
              );
            })
          )}
        </div>

      </div>
    </ManagerLayout>
  );
}
